### Find All
GET http://localhost:8080/songs

### Find
GET http://localhost:8080/songs/1

### CREATE
POST http://localhost:8080/songs/1
Content-Type: application/json

{
  "title": "Title",
  "author": "Authro",
  "year": 2000
}

### PUT
PUT http://localhost:8080/songs
Content-Type: application/json

{
  "title": "Zenon Martynowicz",
  "author": "Oczy bezowe",
  "year": 2000
}

### DELETE
DELETE http://localhost:8080/songs/1

